[toolchain]
package_manager = "yarn"

[features]
resolution = true
seeds = true
init-if-needed = true
skip-lint = false


[programs.localnet]
notes = "A1mqt2qGaBxy7yz3oX2nrxoovG9CgshHQSzyfEVdEZUg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
